AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Match food donors with patrons. Uses Lambda, Lex, RDS'
Parameters:
  KeyIdParameter:
    Type: String
Resources:
  FoodForAllLex2RDS:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: 'Match food donors with patrons. Uses Lambda, Lex, RDS'
      MemorySize: 128
      Timeout: 15
      Policies:
        - KMSDecryptPolicy:
             KeyId: !Ref KeyIdParameter
